---
- hosts: jenkins-master
  become: yes
  tasks:
    - name: Install Java 17
      yum:
        name: java-17-amazon-corretto-devel
        state: present


    - name: Add jenkins repo
      yum_repository:
        name: jenkins
        desctiption: Jenkins-stable
        baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: enable and start jenkins
      service:
        name: jenkins
        state: started
        enabled: true

    - name: open firewall for jenkins
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
      when: ansible_facts.os_family == "RedHat"

    - name: reload firewall
      command: firewall-cmd --reload
      when: ansible_facts.os_family == "RedHat"


