---
- name: Install Jenkins via RPM (safe for Amazon Linux 2)
  hosts: jenkins-master
  become: yes
  tasks:
    - name: Install dependencies
      yum:
        name:
          - java-17-amazon-corretto-devel
          - git
          - wget
        state: present

    - name: Download Jenkins RPM
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins-2.426.1-1.1.noarch.rpm
        dest: /tmp/jenkins.rpm

    - name: Install Jenkins from RPM
      yum:
        name: /tmp/jenkins.rpm
        state: present

    - name: Enable and start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started

