---
- name: Install Jenkins
  hosts: jenkins-master
  become: yes
  tasks:
    - name: Import Jenkins repository key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins repository
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install Java 17
      yum:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
        enablerepo: jenkins

    - name: Ensure Jenkins is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start (give time for plugins to initialize)
      wait_for:
        port: 8080
        delay: 10
        timeout: 300
